### ISSUE TITLE
Some users report the csproj files are not getting loaded

### ISSUE THREAD

**Issue by carlossanlop** [carlossanlop/DocsPortingTool#36]
Some people are reporting that the tool is not working for them because they are seeing this error when the tool attempts to load the `Project` instance:

```
Diagnostic messages found in workspace.OpenProjectAsync - 
D:\runtime\src\libraries\System.Runtime.Intrinsics\src\System.Runtime.Intrinsics.csproj: 
Failure - Msbuild failed when processing the file 'D:\runtime\src\libraries\System.Runtime.Intrinsics\src\System.Runtime.Intrinsics.csproj'
with message: The SDK resolver type "WorkloadSdkResolver" failed to load.
Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
The system cannot find the file specified. 
```

Santi and I are investigating it.

**Comment by carlossanlop** [comment]
We have narrowed down this issue to machines where 6.0 Prev1 is the latest SDK installed. In machines where 5.0 is the latest SDK, it does not repro.

I know this is the case for @tannergooding . @eiriktsarpalis is this your case too?

**Comment by ericstj** [comment]
Could be caused by the recent changes to pre-req 6.0 preview 1 for dotnet/runtime.  If I had to guess it looks like you're loading the latest (6.0) MSBuild in a 5.0 process.  Do you need to run in proc?   If you need to run in proc then the tool will likely need to run on the same framework version as is pre-req'ed by the repo's global.json.

**Comment by ericstj** [comment]
I hit this and was able to workaround it by making the app target `net6.0`.
